# Generated by Django 4.0.2 on 2022-03-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_customeraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='allbills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('accountno', models.IntegerField()),
                ('rent', models.IntegerField()),
                ('security', models.IntegerField()),
                ('bill', models.IntegerField()),
                ('remaining', models.IntegerField()),
                ('total', models.IntegerField()),
                ('paid', models.IntegerField()),
            ],
        ),
    ]
